spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB
  datasource:
    url: jdbc:postgresql://feed-db:5432/feeddb
    driver-class-name: org.postgresql.Driver
    username: feeddbuser
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      org:
        hibernate:
          dialect: PostgreSQLDialect

server:
  port: 8080