spring:
  datasource:
    url: jdbc:postgresql://messaging-db:5432/messagingdb
    driver-class-name: org.postgresql.Driver
    username: messagingdbuser
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      org:
        hibernate:
          dialect: PostgreSQLDialect

server:
  port: 8080